### ISSUE TITLE
Cannot add a bridged Accessory with the same UUID as another bridged Accessory

### ISSUE THREAD

**Issue by VincenzoKoestler** [Kienz/homebridge-unifi-poe-control#2]
Thank you so much for this plugin, it is amazing! Today, my Hoobs apparently updated itself and now its not longer working though.

I always get the following error: 
Only the first configured port of every switch shows up now.
`Error getting devices: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory`

**Comment by Kienz** [comment]
Can you post your config.

**Comment by VincenzoKoestler** [comment]
```
{
    "platform": "UniFiPoeControl",
    "name": "UniFi PoE",
    "url": "https://10.0.0.1",
    "username": "mail",
    "password": "password",
    "refreshInterval": 50000,
    "ports": [
        {
            "mac": "78:45:52:81:7b:ed",
            "idx": 1,
            "name": "Kamera1",
            "onMode": "auto"
        },
        {
            "mac": "78:45:52:81:7b:ed",
            "idx": 2,
            "name": "Kamera2",
            "onMode": "auto"
        },
        {
            "mac": "78:45:52:81:7b:ed",
            "idx": 3,
            "name": "Kamera3",
            "onMode": "auto"
        },
        {
            "mac": "78:45:52:81:7b:ed",
            "idx": 4,
            "name": "Kamera4",
            "onMode": "auto"
        }
    ]
}
```

**Comment by Kienz** [comment]
Should be fixed with v1.0.1

**Comment by VincenzoKoestler** [comment]
That was blazing fast! Unfortunately, the issue still persists...

Edit: Clearing cached devices fixed it! Thanks a lot for the quick help!! Amazing work :)
